import type { Metadata } from "next";

//import "./globals.css";
import NavBar from "../components/front-components/NavBar";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import prisma from "@/lib/db";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = getKindeServerSession();
  const user = await getUser();

  let authenticated;
  if (user) {
    const dbUser = await prisma.user.findUnique({ where: { id: user.id } });
    if (!dbUser) {
      authenticated = false;
    } else {
      authenticated = true;
    }
  } else {
    authenticated = false;
  }

  return (
    <>
      <NavBar authenticated={authenticated} />
      <main>{children}</main>
    </>
  );
}
